<?php
 $memID=$_POST['m_id'];
 $uname=$_POST['u_name'];
 $stname=$_POST['street_name'];
 $city=$_POST['city'];
 $zipcode=$_POST['zipcode'];
 $state=$_POST['state'];
 $gender=$_POST['gender'];
 $dob=$_POST['dob'];
 $phn=$_POST['mobile'];
 $email=$_POST['email'];
 $jdate=$_POST['jdate'];
 $plan=$_POST['plan'];

 $plan_file = fopen("member_details.txt","a");
 fwrite($plan_file,$memID);
 fwrite($plan_file,"|");
 fwrite($plan_file,$uname);
 fwrite($plan_file,"|");
 fwrite($plan_file,$stname);
 fwrite($plan_file,"|");
 fwrite($plan_file,$city);
 fwrite($plan_file,"|");
 fwrite($plan_file,$zipcode);
 fwrite($plan_file,"|");
 fwrite($plan_file,$state);
 fwrite($plan_file,"|");
 fwrite($plan_file,$gender);
 fwrite($plan_file,"|");
 fwrite($plan_file,$dob);
 fwrite($plan_file,"|");
 fwrite($plan_file,$phn);
 fwrite($plan_file,"|");
 fwrite($plan_file,$email);
 fwrite($plan_file,"|");
 fwrite($plan_file,$jdate);
 fwrite($plan_file,"|");
 fwrite($plan_file,$plan);
 fwrite($plan_file,"#\n");
 fclose($plan_file);

 $plan_file = fopen("health_details.txt","a");
 fwrite($plan_file,$memID);
 fwrite($plan_file,"|");
 fwrite($plan_file,$uname);
 fwrite($plan_file,"|");
 fwrite($plan_file,$gender);
 fwrite($plan_file,"|");
 fwrite($plan_file,$dob);
 fwrite($plan_file,"|");
 fwrite($plan_file,$phn);
 fwrite($plan_file,"|");
 fwrite($plan_file,$jdate);
 fwrite($plan_file,"|");
 fwrite($plan_file,"-");
 fwrite($plan_file,"|");
 fwrite($plan_file,"-");
 fwrite($plan_file,"|");
 fwrite($plan_file,"-");
 fwrite($plan_file,"|");
 fwrite($plan_file,"-");
 fwrite($plan_file,"#\n");
 fclose($plan_file);
 echo "<head><script>alert('Member Added Succefsully =)');</script></head>";
 ?> <script> window.location.replace('new_entry.php'); </script>